### ISSUE TITLE
Call to a member function GetFixturesByDateIntervalAndLeague() on a non-object

### ISSUE THREAD

**Issue by hdushku** [drsdre/yii2-xmlsoccer#1]
When I try the code in demo mode:
`try{
    $client = new \XMLSoccer\Client([
        'api_key' => 'xxx',
        'service_url' => 'http://www.xmlsoccer.com/FootballDataDemo.asmx',
    ]);
    $fixtures=$soccer->GetFixturesByDateIntervalAndLeague(array("league"=>3,"startDateString"=>"2014-08-01 00:00","endDateString"=>"2014-09-30 00:00"));
    var_dump($result);
}
catch(XMLSoccerException $e){
    echo "XMLSoccerException: ".$e->getMessage();
}`
 it shows the error:
Call to a member function GetFixturesByDateIntervalAndLeague() on a non-object

**Comment by drsdre** [comment]
Examples used the wrong parameter name ($soccer). I've updated them.

Thanks for reporting.

Andre
